
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - ./backend/.env  # Load environment variables for the backend
    networks:
      - mern-stack-network

  client:
    build: ./client
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    env_file:
      - ./client/.env  # Load environment variables for frontend build
    networks:
      - mern-stack-network

networks:
  mern-stack-network:
    driver: bridge
